---

# for fetching assets
aws_access_key: AKIAIKLSGHEVQ47ST
aws_secret_key: 0OyPyqkGhFKWS1s+R2or4eBA0HxKd4Fg6eyD8
asset_tag: 20141216.1355

environment: develop
chromedriver: /usr/bin/chromedriver
default_tolerance: 8
browser: firefox

url_postfix: dokku.bionano.autodesk.com

facebookEmail: yann.bertaud@autodesk.com
facebookPassword: foobar123

transcripticAPIKey: BQhS2ng3M2UBf3a5-fts
transcripticEmail: yann.bertaud@autodesk.com
transcripticPassword: foobar123
transcripticOrganization: autodeskyann

# this is url for the laptop sitting in the closet for remote web driver
remoteWebDriverURL: http://sfoush302a0L4

# or set a single token at the top level
# token:

environments:
  develop:
    consumerkey: d0a95598-8357-4668-90f8-37d887517b3b
    consumersecret: a2846bd3-1c24-40e8-abd1-00eaf1f26e74
    login:
    password: 
    uri_root: https://localhost:9000/#/
    token: "MJeTXKeSnDz8dr3khIqA9vJD+Hg="

  qa:
    browser: chrome
    consumerkey: d0a95598-8357-4668-90f8-37d887517b3b
    consumersecret: a2846bd3-1c24-40e8-abd1-00eaf1f26e74
    login:
    password:
    uri_root: https://wla-qa.dokku.bionano.autodesk.com
    token: "MJeTXKeSnDz8dr3khIqA9vJD+Hg="


  production:
    browser: chrome
    consumerkey: d0a95598-8357-4668-90f8-37d887517b3b
    consumersecret: a2846bd3-1c24-40e8-abd1-00eaf1f26e74
    login:
    password:
    uri_root: https://wla.bionano.autodesk.com
    token: "MJeTXKeSnDz8dr3khIqA9vJD+Hg="


# window size defaults
viewport:
  width: 1400
  height: 1024

# until we have a library for fetching images from autodesk prime - here are some
# hard coded images
images:

